name: CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: cargo install cargo-audit cargo-deny cargo-tarpaulin cargo-chef

      - name: Security check
        run: cargo audit

      - name: Dependency check
        run: cargo deny check

      - name: Test coverage gate
        run: cargo tarpaulin --fail-under 80

      - name: Build using cargo chef
        uses: |
          cargo chef prepare --recipe-path recipe.json
          cargo chef cook --recipe-path recipe.json
          cargo build --release      

  
